## Getting started with Jupyter notebooks

### Running a cell
To execute code within a cell, select that cell and either (1) hit `Shift` and `Enter` or (2) hit the run button (the right pointing arrow) above.

In [1]:
1 + 1
2 + 2

4

If you're new to jupyter notebooks, note that only the last line of a cell prints by default when you execute that cell and that you can suppress this output with a semicolon

In [2]:
1 + 1
2 + 2;

### How to get docs for Julia functions

To get docs for a function you're not familiar with, precede it with a question mark. (This works at the REPL too!)

In [3]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` followed by a newline. If `io` is not supplied, prints to [`stdout`](@ref).

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello, world")

julia> String(take!(io))
"Hello, world\n"
```


In [6]:
?sort

search: sort sort! sortperm sortperm! sortslices Cshort issorted QuickSort



```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Array{Int64,1}:
 1
 2
 3

julia> v
3-element Array{Int64,1}:
 3
 1
 2
```

---

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Array{Int64,2}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Array{Int64,2}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Array{Int64,2}:
 3  4
 1  2
```


In [19]:
A = [4 3 ; 1 2 ]

2×2 Array{Int64,2}:
 4  3
 1  2

In [20]:
sort(A, dims=1) # dims=1 : column(直)方向

2×2 Array{Int64,2}:
 1  2
 4  3

In [21]:
sort(A, dims=2) # dims=2 : row(橫)方向

2×2 Array{Int64,2}:
 3  4
 1  2

In [ ]:
sort! #'!'會對函數參數做修改!

### How to use shell commands

Type `;` and then you can use shell commands. For example,

In [22]:
;ls

00. Jupyter_notebooks.ipynb
01. Getting started.ipynb
02. Strings.ipynb
03. Data structures.ipynb
04. Loops.ipynb
05. Conditionals.ipynb
06. Functions.ipynb
07. Packages.ipynb
08. Plotting.ipynb
09. Julia is fast.ipynb
10. Multiple dispatch.ipynb
10.1 Multiple dispatch.ipynb
11. Basic linear algebra.ipynb
12. Factorizations and other fun.ipynb
AutoDiff.ipynb
Exercise_solutions.ipynb
Exploring_benchmarking_and_performance.ipynb
Exploring_benchmarking_and_performance_solutions.ipynb
LICENSE.md
Local_installations.ipynb
README.md
Reduce and Parallel Prefix - JuliaBox.ipynb
Working with matrices.ipynb
calculate_pi.ipynb
calculate_pi_solution.ipynb
compressing_an_image.ipynb
compressing_an_image_solutions.ipynb
create_a_caesar_cipher.ipynb
create_a_caesar_cipher_solutions.ipynb
derfunc.gif
images
long-version
short-version


In [ ]:
;pwd

Shell commands also work at the REPL!